Changes in topsize and insfx

diff --git a/Desktop/Exercises/insfx b/Desktop/Exercises/insfx
--- a/Desktop/Exercises/insfx
+++ b/Desktop/Exercises/insfx
@@ -49,7 +49,7 @@ do
 	then
 	    suffix=$i
 	elif [[ -z $directory ]]
-	then
+	then 
 	    directory=$i
 	    find_command+=("$directory")
 	else
@@ -65,24 +65,42 @@ do
     fi
     shift
 done
+if [[ -z $suffix ]]
+then
+	echo "ERROR"
+	echo "There is no suffix to insert" >&2
+	exit 2
+elif [[ -z $directory ]]
+then
+	echo "ERROR"
+	echo "There is no directory to find" >&2
+	exit 2
+elif [[ ${#find_command[@]} -le 2 ]]
+then
+	echo "ERROR"
+	echo "You did not type any mask to find" >&2
+	exit 2
+fi
 
 if [[ -d $directory ]]
 then
+    echo ${find_command[@]}
     "${find_command[@]}" | sort -u | while read file
 	do
 	    aux=${file##*"/"}
 	    aux1=${file%"$aux"}
 	    file_name=${aux%.*}
 	    ext=${file#*"$file_name"}
+	    echo $aux $aux1 $file_name $ext
 	    if [[ ! -z $var_d ]] || [[ ! -z $var_v ]]
 	    then
 		echo "$file ------> $aux1$file_name$suffix$ext"
 		if [[ ! -z $var_v ]]
 		then
-		    mv -- "$file" "$file_name$suffix$ext"
+		    mv -- "$file" "$aux1$file_name$suffix$ext"
 		fi
 	    else
-		mv -- "$file" "$file_name$suffix$ext"
+		mv -- "$file" "$aux1$file_name$suffix$ext"
 	    fi
 	done
 else
